### PR TITLE
Atmos. create  buildFrom.dm

### PR DESCRIPTION
**Pull request by Dennok**
Look on this.
I create buildFrom.dm for	  all proc/buildFrom() and fill it. It work.

### CODE REVIEW

**Comment by PsiOmegaDelta** [comment]
This contains about 46 too many commits.

**Comment by Dennok** [comment]
yes

**Comment by Dennok** [comment]
i update my fork and gat many new commits what no it this

**Comment by Dennok** [comment]
https://github.com/Baystation12/Baystation12/pull/9329/commits

**Comment by Dennok** [comment]
i truing but cant fork you  PsiOmegaDelta:Atmos

**Comment by PsiOmegaDelta** [comment]
First if you haven't create a new remote repository using either of following Git commands:
````git remote add PsiOmegaDelta git@github.com:PsiOmegaDelta/Baystation12.git````
OR
````git remote add PsiOmegaDelta https://github.com/PsiOmegaDelta/Baystation12.git````
**PsiOmegaDelta** will become the name of the remote repository and the following is obviously the address.

Then you should be able to execute the command:
````git fetch --progress "PsiOmegaDelta " ````
Gets all the branches in the remote repository named **PsiOmegaDelta**

Finally you should be able to checkout the branch, using the command:
````git checkout --force -B "Atmos" "PsiOmegaDelta/Atmos"````
Checks out my branch **Atmos**, overriding any previous branches named the same, so be careful.
You can drop the --force part if you want to be on the same side.


The same thing can be repeated for Baystation12.
Simply replace **PsiOmegaDelta** with **Baystation12** and the address with ````https://github.com/Baystation12/Baystation12.git```` or ````git@github.com:Baystation12/Baystation12.git````.

**Comment by Dennok** [comment]
thank

**Comment by PsiOmegaDelta** [comment]
Do ask if any issues come up, would like to see a clean PR.

**Comment by Dennok** [comment]
What me update repositry dont making PR?

**Comment by Dennok** [comment]
i have  a problems

**Pull request closed without merging**
